# Site settings
title: concon121@github
email: connor@cbscl.co.uk
description: Random musings on the things I get up to!
github_username: concon121
permalink: none
paginate: 5

# Build settings
markdown:            kramdown
highlighter:         rouge
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

sass:
  sass_dir: assets/css
  style: :nested
