# Site settings
title: concon121@github
email: connor.bray@icloud.com
description: Random musings on the things I get up to!
url: "http://generation-y.cbscl.co.uk"
baseUrl: "/generation-y.cbscl.co.uk"
github_username:  concon121
permalink: none
paginate: 5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

sass:
  sass_dir: assets/css
  style: :nested
