# Site settings
title: concon121@github
email: connor.bray@icloud.com
description: Random musings on the things I get up to!
baseurl: "/concon121.github.io"
url: "http://concon121.github.io"
github_username:  concon121
permalink: /blog/:year/:title/

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
