# Site settings
title: concon121@github
email: connor.bray@icloud.com
description: Random musings on the things I get up to!
baseurl: "/"
github_username:  concon121

paginate: 5


# Build settings
markdown:            kramdown
highlighter:         pygments
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

sass:
  sass_dir: assets/css
  style: :nested
