title:  "Generation Y"
tagline: "Rantings of a software developer"
description: "Rantings of a software developer"

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Projects', file: 'projects.html'}
- {name: 'Blog', file: 'blog.html'}
- {name: 'Sample Posts', file: 'sample-posts.html'}
- {name: 'Documentation', file: 'documentation.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'facebook', link: 'https://www.facebook.com/connor.bray'}
- {icon: 'instagram', link: 'https://instagram.com/concon121'}
- {icon: 'envelope', link: 'mailto:connor@cbscl.co.uk'}
- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
